# HTTP — ACME challenge + redirect ke HTTPS
server {
    listen 80;
    listen [::]:80;
    server_name siswa.pallrzki.my.id;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type "text/plain";
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# HTTPS
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name siswa.pallrzki.my.id;

    ssl_certificate     /etc/letsencrypt/live/siswa.pallrzki.my.id/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/siswa.pallrzki.my.id/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    root /var/www/porto;
    index index.html;

    add_header X-Content-Type-Options nosniff always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;
    add_header X-Frame-Options SAMEORIGIN always;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(css|js|svg|png|jpg|jpeg|gif|ico|woff2)$ {
        expires 7d;
        add_header Cache-Control "public";
    }
}
